### ISSUE TITLE
Crash-restart on message type done

### ISSUE THREAD

**Issue by nof20** [nof20/ThreadMarketData#13]
Mar 03, 2016 11:44:01 PM main.RealtimeOrderBookBuilder run
SEVERE: Caught exception trying to take from inbound queue: delta [type done, time 2016-03-03T23:44:01.538094Z, product_id BTC-USD, sequence 729020835, order_id c5c67b0b-1d55-463d-b513-c0bacdeb4d55, side sell, order_type market, reason filled, ]
Mar 03, 2016 11:44:01 PM main.RealtimeOrderBookBuilder run
SEVERE: Received delta update out of sequence, re-initializing
Mar 03, 2016 11:44:01 PM main.sockets.MarketDataSocket onClose
INFO: Websocket onClose: 1001 Shutdown

**Comment by nof20** [comment]
Mar 04, 2016 12:45:03 PM main.RealtimeOrderBookBuilder run
SEVERE: Caught exception trying to take from inbound queue: delta [type done, time 2016-03-04T12:45:03.638142Z, product_id BTC-USD, sequence 730979019, order_id 691dc53c-2728-4a48-bb69-f8f47613f0fd, side buy, order_type market, reason filled, ]
java.lang.NullPointerException
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at main.RealtimeOrderBookBuilder.run(RealtimeOrderBookBuilder.java:156)
	at java.lang.Thread.run(Thread.java:745)
Mar 04, 2016 12:45:03 PM main.RealtimeOrderBookBuilder run
SEVERE: Received delta update out of sequence, re-initializing

**Comment by nof20** [comment]
Seems to be due to the fact that "done" market orders are not in the order book, so we cannot find them in the order map (by price) in order to close them.  I thought I fixed this issue a long time ago, but it must have been in another place in the code.  Difference in stack traces must be between Oracle JRE/OpenJRE handling of Double.parseDouble(null).
